// <auto-generated />
using BTCPayApp.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTCPayApp.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ark")
                .HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("BTCPayApp.Core.Data.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Value")
                        .HasColumnType("BLOB");

                    b.HasKey("Key");

                    b.ToTable("Settings", "ark");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkIntentEntity", b =>
                {
                    b.Property<string>("IntentTxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitmentTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeleteProof")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteProofMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IntentId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("PartialForfeits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterProof")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisterProofMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignerDescriptor")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValidFrom")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ValidUntil")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IntentTxId");

                    b.HasIndex("IntentId")
                        .IsUnique()
                        .HasFilter("\"IntentId\" IS NOT NULL");

                    b.ToTable("Intents", "ark");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkIntentVtxoEntity", b =>
                {
                    b.Property<string>("IntentTxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VtxoTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VtxoTransactionOutputIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LinkedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("IntentTxId", "VtxoTransactionId", "VtxoTransactionOutputIndex");

                    b.HasIndex("VtxoTransactionId", "VtxoTransactionOutputIndex");

                    b.ToTable("IntentVtxos", "ark");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkSwapEntity", b =>
                {
                    b.Property<string>("SwapId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WalletId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractScript")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpectedAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Invoice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SwapType")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("SwapId", "WalletId");

                    b.HasIndex("WalletId");

                    b.HasIndex("ContractScript", "WalletId");

                    b.ToTable("Swaps", "ark");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkWalletContractEntity", b =>
                {
                    b.Property<string>("Script")
                        .HasColumnType("TEXT");

                    b.Property<string>("WalletId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActivityState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ContractData");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Script", "WalletId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletContracts", "ark");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkWalletEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountDescriptor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("TODO_MIGRATION");

                    b.Property<int>("LastUsedIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wallet")
                        .HasColumnType("TEXT");

                    b.Property<string>("WalletDestination")
                        .HasColumnType("TEXT");

                    b.Property<int>("WalletType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Wallet")
                        .IsUnique()
                        .HasFilter("\"Wallet\" IS NOT NULL");

                    b.ToTable("Wallets", "ark");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.VtxoEntity", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionOutputIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArkTxid")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitmentTxids")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("ExpiresAtHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("Metadata");

                    b.Property<bool>("Preconfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Recoverable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettledByTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpentByTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Unrolled")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId", "TransactionOutputIndex");

                    b.ToTable("Vtxos", "ark");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkIntentVtxoEntity", b =>
                {
                    b.HasOne("NArk.Storage.EfCore.Entities.ArkIntentEntity", "Intent")
                        .WithMany("IntentVtxos")
                        .HasForeignKey("IntentTxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NArk.Storage.EfCore.Entities.VtxoEntity", "Vtxo")
                        .WithMany("IntentVtxos")
                        .HasForeignKey("VtxoTransactionId", "VtxoTransactionOutputIndex")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intent");

                    b.Navigation("Vtxo");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkSwapEntity", b =>
                {
                    b.HasOne("NArk.Storage.EfCore.Entities.ArkWalletEntity", "Wallet")
                        .WithMany("Swaps")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NArk.Storage.EfCore.Entities.ArkWalletContractEntity", "Contract")
                        .WithMany("Swaps")
                        .HasForeignKey("ContractScript", "WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkWalletContractEntity", b =>
                {
                    b.HasOne("NArk.Storage.EfCore.Entities.ArkWalletEntity", "Wallet")
                        .WithMany("Contracts")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkIntentEntity", b =>
                {
                    b.Navigation("IntentVtxos");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkWalletContractEntity", b =>
                {
                    b.Navigation("Swaps");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.ArkWalletEntity", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Swaps");
                });

            modelBuilder.Entity("NArk.Storage.EfCore.Entities.VtxoEntity", b =>
                {
                    b.Navigation("IntentVtxos");
                });
#pragma warning restore 612, 618
        }
    }
}
